// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvguqbopovdqogdvqqpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2Z3VxYm9wb3ZkcW9nZHZxcXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTM2NDMsImV4cCI6MjA2MDcyOTY0M30.Z3EA4xMK0d1qk5djdKsqVuEHfn22lCl_vZghgoOBjpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);